Optionally return p-value from param_estimates()
metrumresearchgroup/bbr pull request #497
Opened 2022-06-13 18:38 UTC by barrettk

closes https://github.com/metrumresearchgroup/bbr/issues/458

2022-06-13 18:42 UTC, barrettk commented
Considered adding this functionality to functions like `param_estimates_batch()` and `param_estimates_compare()`, but after inspecting the returned dataframes and required input, I dont think it makes sense to append it to those functions

2022-06-15 14:53 UTC, seth127 commented
@kyleam would you mind reviewing this?

Also, @callistosp take a look at this if you get a second to make sure it's what you had in mind for #458 and that it works how you'd expected.

2022-06-15 17:17 UTC, kyleam requested changes

2022-06-16 15:23 UTC, barrettk commented on R/param-estimates.R
> +      bind_cols(data.frame(pval=.summary$shrinkage_details[length(.summary$shrinkage_details)][[1]][[1]]$pval)) %>%
@kyleam I do like this idea. Only issue is running that command multiple times causes duplicate columns to appear:
![image](https://user-images.githubusercontent.com/18685116/174104544-75d38383-c816-46de-88ff-01035d53dfb8.png)

I still like nesting the functionality within `add_param_shrinkage` though, so will address this

2022-06-16 15:24 UTC, barrettk commented on R/param-estimates.R
> +      bind_cols(data.frame(pval=.summary$shrinkage_details[length(.summary$shrinkage_details)][[1]][[1]]$pval)) %>%
nevermind I take that back, didnt see that you removed the previous call!

2022-06-16 15:38 UTC, barrettk commented
@kyleam how do you feel about the test? It looks like we arent testing `add_param_shrinkage` since its an internal function. I think the integration test (not sure if thats correct terminology in this case) I added should be sufficient, but not 100% confident on that

2022-06-16 16:45 UTC, kyleam approved these changes
@barrettk Thanks, this looks good to me.

Left one minor comment about an unused import.

2022-06-16 16:45 UTC, kyleam commented on R/param-estimates.R
> +#' @importFrom dplyr bind_cols
`bind_cols` is no longer used.

2022-06-16 16:45 UTC, kyleam commented
> @kyleam how do you feel about the test? [...]

I agree, I don't see any value to testing `add_param_shrinkage` directly.

2022-06-16 16:46 UTC, kyleam commented on R/param-estimates.R
> +    assert_numeric(.alpha)
> It did show up as already imported on my end, but ill add another call just to be safe

Right, two functions in `cov-cor.R` already have `@importFrom checkmate assert_numeric`, which why this doesn't trigger an error.

My view is that a function shouldn't rely on `@importFrom`s from other functions (i.e. each function's `@importFrom`s should give a complete list of what imports it needs).  That way if someone modifies the `cov-cor.R` functions in a way that drops an import, they don't have to search around the code base for some other function that is implicitly depending on the import.

2022-06-16 19:31 UTC, barrettk commented
@kyleam unfortunately, making the fix automatically removed your review. Can you approve again?

2022-06-16 19:40 UTC, kyleam approved these changes

2022-06-16 19:49 UTC, merged