Get initial parameter estimates and tweak initial parameter estimates
metrumresearchgroup/bbr pull request #635
Opened 2024-01-10 18:20 UTC by barrettk

### Getting initial parameter estimates
 - The information returned from the prototype function will be needed for the new tweak/jitter function. It currently relies on internal `nmrec` functions, and likely needs to be reworked to be more readable.
 - I think a function like this belongs in `nmrec`, but wanted to develop a prototype in `bbr` to facilitate the conversation in terms of what information I need
 - In the end, we want to export a function *similar* to what I have so far, but with improved formatting; perhaps as a table, similar to `param_estimates()`. The `bbr` function could be a wrapper of the `nmrec` function we develop, but I think the core work should be done in `nmrec`

### Tweaking/Jittering Initial parameter estimates

2024-01-10 18:28 UTC, barrettk commented
Examples so far:

### Setup
```r
source("/data/Projects/package_dev/bbr/tests/testthat/setup-workflow-ref.R", echo=FALSE)
MODEL_DIR_C <- system.file("model", "nonmem", "complex",   package = "bbr")
```

### Example models
These are the examples that have been tested thus far
```r
.mod <- MOD1
.mod <- read_model(file.path(MODEL_DIR_C, "1001"))
.mod <- read_model(file.path(MODEL_DIR_C, "example2_saemimp"))
```

### Example output

Base Model
<details closed>
<summary>MOD1</summary>

```r
> .mod <- MOD1
> get_param_inits(.mod)
$theta
# A tibble: 5 × 3
  low   init  index
  <chr> <chr> <int>
1 0     2         1
2 0     3         2
3 0     10        3
4 NA    0.02      4
5 NA    1         5

$omega
$omega$matrices
$omega$matrices[[1]]
     [,1] [,2]
[1,] 0.05  0.0
[2,] 0.00  0.2


$omega$fixed
$omega$fixed[[1]]
[1] FALSE



$sigma
$sigma$matrices
$sigma$matrices[[1]]
     [,1]
[1,]    1


$sigma$fixed
$sigma$fixed[[1]]
[1] TRUE
```
</details>

Model with multiple records: here we create a combined matrix, which will facilitate passing jittered values to `set_omega()`. If one of the matrices was `FIXED`, we would need additional logic for _not_ overwriting those values
<details closed>
<summary>1001</summary>

```r
> .mod <- read_model(file.path(MODEL_DIR_C, "1001"))
> get_param_inits(.mod)
$theta
# A tibble: 6 × 2
  init               index
  <chr>              <int>
1 -0.574219127214817     1
2 5.67154052944669       2
3 1.03568637508119       3
4 0.241769673098703      4
5 -11.3632385211334      5
6 5.11272713931817       6

$omega
$omega$matrices
$omega$matrices[[1]]
     [,1]
[1,] 0.09

$omega$matrices[[2]]
     [,1] [,2] [,3]
[1,] 0.09 0.00 0.00
[2,] 0.01 0.09 0.00
[3,] 0.01 0.01 0.09


$omega$fixed
$omega$fixed[[1]]
[1] FALSE

$omega$fixed[[2]]
[1] FALSE


$omega$full_matrix
     [,1] [,2] [,3] [,4]
[1,] 0.09 0.00 0.00 0.00
[2,] 0.00 0.09 0.00 0.00
[3,] 0.00 0.01 0.09 0.00
[4,] 0.00 0.01 0.01 0.09


$sigma
$sigma$matrices
$sigma$matrices[[1]]
     [,1] [,2]
[1,] 0.04 0.00
[2,] 0.00 0.04


$sigma$fixed
$sigma$fixed[[1]]
[1] FALSE
```
</details>

**Note:** this model as prior blocks, so the output here is technically incorrect, or at least lacking in terms of differentiating between actual records and priors. Additional logic would be needed to filter these out or error if the expected length wasnt found
<details closed>
<summary>example2_saemimp</summary>

```r
> .mod <- read_model(file.path(MODEL_DIR_C, "example2_saemimp"))
> get_param_inits(.mod)
$theta
# A tibble: 12 × 3
   init  fixed index
   <chr> <chr> <int>
 1 0.7   NA        1
 2 0.7   NA        2
 3 2     NA        3
 4 2.0   NA        4
 5 0.7   NA        5
 6 0.7   NA        6
 7 2.0   NA        7
 8 2.0   NA        8
 9 0.7   NA        9
10 0.7   NA       10
11 0.3   NA       11
12 4     TRUE     12

$omega
$omega$matrices
$omega$matrices[[1]]
      [,1]  [,2]  [,3] [,4]
[1,] 0.500 0.000 0.000  0.0
[2,] 0.001 0.500 0.000  0.0
[3,] 0.001 0.001 0.500  0.0
[4,] 0.001 0.001 0.001  0.5

$omega$matrices[[2]]
     [,1] [,2] [,3] [,4]
[1,] 0.01 0.00 0.00 0.00
[2,] 0.00 0.01 0.00 0.00
[3,] 0.00 0.00 0.01 0.00
[4,] 0.00 0.00 0.00 0.01


$omega$fixed
$omega$fixed[[1]]
[1] FALSE

$omega$fixed[[2]]
[1] TRUE


$omega$full_matrix
      [,1]  [,2]  [,3] [,4] [,5] [,6] [,7] [,8]
[1,] 0.500 0.000 0.000  0.0 0.00 0.00 0.00 0.00
[2,] 0.001 0.500 0.000  0.0 0.00 0.00 0.00 0.00
[3,] 0.001 0.001 0.500  0.0 0.00 0.00 0.00 0.00
[4,] 0.001 0.001 0.001  0.5 0.00 0.00 0.00 0.00
[5,] 0.000 0.000 0.000  0.0 0.01 0.00 0.00 0.00
[6,] 0.000 0.000 0.000  0.0 0.00 0.01 0.00 0.00
[7,] 0.000 0.000 0.000  0.0 0.00 0.00 0.01 0.00
[8,] 0.000 0.000 0.000  0.0 0.00 0.00 0.00 0.01


$sigma
$sigma$matrices
$sigma$matrices[[1]]
     [,1]
[1,]    1


$sigma$fixed
$sigma$fixed[[1]]
[1] TRUE
```
</details>

2024-01-11 22:40 UTC, barrettk commented
## Some examples with the most recent refactor:

```r
.mod <- read_model(file.path(MODEL_DIR_C, "example2_saemimp"))
```
```r
> get_param_inits(.mod)
$thetas
# A tibble: 13 × 3
    init   low    up
   <dbl> <dbl> <dbl>
 1  NA    0     1   
 2   0.7 NA    NA   
 3   0.7  0.67  0.72
 4   2   NA    NA   
 5   2   NA    NA   
 6   0.7 NA    NA   
 7   0.7 NA    NA   
 8   2   NA    NA   
 9   2   NA    NA   
10   0.7 NA    NA   
11   0.7 NA    NA   
12   0.3 NA    NA   
13   4   NA    NA   

$omegas
      [,1]  [,2]  [,3] [,4] [,5] [,6] [,7] [,8]
[1,] 0.500    NA    NA   NA   NA   NA   NA   NA
[2,] 0.001 0.500    NA   NA   NA   NA   NA   NA
[3,] 0.001 0.001 0.500   NA   NA   NA   NA   NA
[4,] 0.001 0.001 0.001  0.5   NA   NA   NA   NA
[5,]    NA    NA    NA   NA 0.01   NA   NA   NA
[6,]    NA    NA    NA   NA 0.00 0.01   NA   NA
[7,]    NA    NA    NA   NA 0.00 0.00 0.01   NA
[8,]    NA    NA    NA   NA 0.00 0.00 0.00 0.01

$sigmas
     [,1]
[1,]    1
```

### Flag fixed parameters
```r
> get_param_inits(.mod, flag_fixed = TRUE)
$thetas
# A tibble: 13 × 4
    init   low    up fixed
   <dbl> <dbl> <dbl> <lgl>
 1  NA    0     1    FALSE
 2   0.7 NA    NA    TRUE 
 3   0.7  0.67  0.72 FALSE
 4   2   NA    NA    FALSE
 5   2   NA    NA    FALSE
 6   0.7 NA    NA    FALSE
 7   0.7 NA    NA    FALSE
 8   2   NA    NA    FALSE
 9   2   NA    NA    FALSE
10   0.7 NA    NA    FALSE
11   0.7 NA    NA    FALSE
12   0.3 NA    NA    FALSE
13   4   NA    NA    TRUE 

$omegas
      [,1]  [,2]  [,3] [,4] [,5] [,6] [,7] [,8]
[1,] 0.500    NA    NA   NA   NA   NA   NA   NA
[2,] 0.001 0.500    NA   NA   NA   NA   NA   NA
[3,] 0.001 0.001 0.500   NA   NA   NA   NA   NA
[4,] 0.001 0.001 0.001  0.5   NA   NA   NA   NA
[5,]    NA    NA    NA   NA 0.01   NA   NA   NA
[6,]    NA    NA    NA   NA 0.00 0.01   NA   NA
[7,]    NA    NA    NA   NA 0.00 0.00 0.01   NA
[8,]    NA    NA    NA   NA 0.00 0.00 0.00 0.01
attr(,"nmrec_flags")
attr(,"nmrec_flags")$fixed
      [,1]  [,2]  [,3]  [,4] [,5] [,6] [,7] [,8]
[1,] FALSE    NA    NA    NA   NA   NA   NA   NA
[2,] FALSE FALSE    NA    NA   NA   NA   NA   NA
[3,] FALSE FALSE FALSE    NA   NA   NA   NA   NA
[4,] FALSE FALSE FALSE FALSE   NA   NA   NA   NA
[5,]    NA    NA    NA    NA TRUE   NA   NA   NA
[6,]    NA    NA    NA    NA TRUE TRUE   NA   NA
[7,]    NA    NA    NA    NA TRUE TRUE TRUE   NA
[8,]    NA    NA    NA    NA TRUE TRUE TRUE TRUE


$sigmas
     [,1]
[1,]    1
attr(,"nmrec_flags")
attr(,"nmrec_flags")$fixed
     [,1]
[1,] TRUE
```

### Tweaking initial estimates

#### Start
```
;Initial THETAs
$THETA
(0,,1) ;[LCLM2]
( 0.7 FIX) ;[LCLM]
(0.67, 0.7, 0.72) ;[LCLF]
( 2 )   ;[CLAM]
( 2.0);[CLAF]
( 0.7 ) ;[LV1M]
( 0.7 ) ;[LV1F]
( 2.0 )   ;[V1AM]
( 2.0 )   ;[V1AF]
( 0.7 ) ;[MU_3]
(  0.7 );[MU_4]
( 0.3 )     ;[SDSL]
```

#### Tweak values
```r
tweak_initial_estimates(
    .mod
    .p = 0.1,
    tweak = c("theta", "sigma", "omega"),
    digits = 2
)
```

#### After Tweaking
```
;Initial THETAs
$THETA
(0,,1) ;[LCLM2] # If no estimate is found, treat as fixed (skip)
( 0.7 FIX) ;[LCLM] # skip fixed parameters
(0.67, 0.72, 0.72) ;[LCLF] # If tweaked value would be outside of one of the bounds, set to the bound
( 1.9 )   ;[CLAM] # Otherwise tweak the value by the sampled percentage
( 2.1);[CLAF]
( 0.76 ) ;[LV1M]
( 0.67 ) ;[LV1F]
( 2.2 )   ;[V1AM]
( 1.8 )   ;[V1AF]
( 0.73 ) ;[MU_3]
(  0.68 );[MU_4]
( 0.27 )     ;[SDSL]
```

2024-01-16 21:44 UTC, barrettk commented
Hey @seth127, I just marked you for an intermediate review. Some things that still need to be done or talked about:

### Updates
 - Update the required `nmrec` version in a few functions/tests, along with the drone yaml, once a new version of `nmrec` is released
    - This may require a slight refactor if anything changes on the `nmrec` side
    - Wanted to talk about whether it made sense to update drone vs wait till we migrated to github actions.

### Discussions
 - I didnt right up any tests for the `initial_estimates` wrapper given the nature of it, but let me know if you think I should
 - Let me know how you feel about the current tests for getting the initial estimates (pretty minimal given that `nmrec` will handle most operations)
 - Discussion regarding the test framework for jittering the initial estimates
 - Any thoughts on setting a seed? (see my commit message [d169643](https://github.com/metrumresearchgroup/bbr/pull/635/commits/d169643279beb11b6f48a214820ed0bd032fdbf9))
 - Argument and function names

Im going to spend a little more time on documentation, but after that I was planning on waiting for a first review/some other parts to move along

2024-01-17 18:11 UTC, barrettk commented on R/tweak-initial-estimates.R
> +#'
@kyleam when you have a minute, im curious if you have any pointers/opinions on these docs

2024-01-18 17:36 UTC, seth127 requested changes
This is looking good, just few minor comments from this review. 

I also want to note that we still have two outstanding questions about the omega (and also sigma?) matrices:

1. Do we tweak the off-diagonals (if they're defined in the control stream) or not?
2. How should we handle checking for (and possibly forcing) positive definiteness?

Either way, as discussed with @barrettk offline, our current plan for that is:

* Continue with this PR and merge it to `main` once review comments are addressed and the relevant `nmrec` changes have landed (https://github.com/metrumresearchgroup/nmrec/pull/30)
* @barrettk to create a new issue to specifically address the outstanding matrix questions mentioned above.
* Address that new issue in a separate PR.
* Plan to _not_ make a `bbr` release until all of that ^ has landed on `main`.

2024-01-18 18:30 UTC, barrettk commented on R/tweak-initial-estimates.R
> +  attr(.mod, "tweak_estimates.seed") <- seed
As discussed offline, yeah I fully agree with removing this

2024-01-19 18:45 UTC, barrettk commented
As @seth127 noted, we will need a separate PR to address [these issues](https://github.com/metrumresearchgroup/bbr/issues/640). The new `tweak_initial_estimates()` function works for `THETA` parameters, but is flawed in its handling of matrices. Still needed:

 - evaluate positive-definiteness of the tweaked matrix, and adjust if needed
 - In the event of a correlation matrix, the tweaked matrix must first be converted to a covariance matrix before evaluating positive-definiteness/making necessary adjustments, and then converting it back to the correct format (variance on diagonal, correlation on off-diagonal)

2024-01-23 17:19 UTC, barrettk commented
@seth127 something I just thought about. This is related to a conversation @kyleam and I had regarding the handling of prior blocks that follow the old naming convention (see [final thoughts](https://github.com/metrumresearchgroup/nmrec/issues/29#issuecomment-1887682553)).

Basically, prior blocks currently get "grouped" when creating the combined matrix. This would also occur for THETA records:

<details closed>
<summary>Example</summary>

```r
> MODEL_DIR_X
[1] "inst/model/nonmem/complex"
> .mod <- read_model(file.path(MODEL_DIR_X, "example2_saemimp"))
```

```r
ctl <- nmrec::read_ctl(get_model_path(.mod))
> nmrec::extract_omega(ctl)
      [,1]  [,2]  [,3] [,4] [,5] [,6] [,7] [,8]
[1,] 0.500    NA    NA   NA   NA   NA   NA   NA
[2,] 0.001 0.500    NA   NA   NA   NA   NA   NA
[3,] 0.001 0.001 0.500   NA   NA   NA   NA   NA
[4,] 0.001 0.001 0.001  0.5   NA   NA   NA   NA
[5,]    NA    NA    NA   NA 0.01   NA   NA   NA
[6,]    NA    NA    NA   NA 0.00 0.01   NA   NA
[7,]    NA    NA    NA   NA 0.00 0.00 0.01   NA
[8,]    NA    NA    NA   NA 0.00 0.00 0.00 0.01
```

In the `$OMEGA` records below, only the first one is an actual record:

```
;Initial OMEGAs
$OMEGA BLOCK(4)
0.5  ;[p]
0.001  ;[f]
0.5  ;[p]
0.001 ;[f]
0.001 ;[f]
0.5  ;[p]
0.001 ;[f]
0.001 ;[f]
0.001 ;[f]
0.5 ;[p]

; Degrees of freedom to OMEGA prior matrix:
$THETA 4 FIX
; Prior OMEGA matrix
$OMEGA BLOCK(4)
0.01 FIX
0.0  0.01
0.0 0.0 0.01
0.0 0.0 0.0 0.01
```
</details>

I was reminded about this conversation when doing some preliminary testing for the positive-definiteness, but now im not sure if we should address this in this PR, given that it also implicates `THETA` records. 

Im not really sure how to handle this. In the case of `inherit_param_estimates()`, Kyle compares the length of the passed-in values (from `model_summary` output) to the detected number of record values. We cant do that here though, as the length of the passed-in values is *determined* by the length of the fetched initial estimates. I dont see a way around parsing the `PRIOR` block ***or*** allowing priors to be jittered.

2024-01-23 22:29 UTC, kyleam commented
> Basically, prior blocks currently get "grouped" when creating the combined matrix.

My opinion for how to proceed is what I said in the issue you linked: we should document that using non-informative  recordnames for priors is not supported with this feature.

2024-01-24 04:10 UTC, seth127 commented
@kyleam said

> we should document that using non-informative record names for priors is not supported with this feature.

and I think I agree with that, in principle. However, in practice, we never know that they're using non-informative priors in this case.

Above, @barrettk said

> [`nmrec`] compares the length of the passed-in values (from `model_summary` output) to the detected number of record values. We cant do that here though, as the length of the passed-in values is _determined by_ the length of the fetched initial estimates.

I've looked through the code a bit and I'm pretty sure that's right. My evidence:

* @kyleam I think you're saying we should just let this case fall through to [this error](https://github.com/metrumresearchgroup/nmrec/blob/2885bc0/R/set-param.R#L189-L204)
* But that error only gets triggered when `length(values) != len_expected`
* In the `inherit_param_estimates()` call, `values` is ultimately coming from a `model_summary()` on a previously executed model (e.g. [here](https://github.com/metrumresearchgroup/bbr/blob/d6e4dfd/R/inherit-param-estimates.R#L77)). At that point, we know they're all real parameters (and not a non-informative priors), and so the mismatch/error in `set_param()` gets triggered.
* However, in the `tweak_initial_estimates()` call, the thing that is eventually passed to `values` is coming from the `nmrec::extract_*` functions ([here](https://github.com/metrumresearchgroup/bbr/blob/c616be4/R/tweak-initial-estimates.R#L66), which leads to [here](https://github.com/metrumresearchgroup/bbr/blob/c616be4/R/initial-estimates.R#L90-L93)). And since the `extract_*` don't differentiate between real parameters and non-informative priors... we never get the mismatch.



<details><summary>I also tried this empirically and saw the same thing:</summary>

I tried with `example2_saemimp` model, but **first I had to remove the `FIX` from the final `THETA`** (which is actually a prior) to verify that it would indeed get tweaked. And it does:

```r
.mod <- read_model(file.path(MODEL_DIR_X, "example2_saemimp"))
tweak_initial_estimates(.mod)
```

results in this

![Screenshot 2024-01-23 at 10 33 28 PM](https://github.com/metrumresearchgroup/bbr/assets/7806083/76d89171-c927-4591-9dff-0cc18464b968)

</details>

Soooooo... that means we can't just leave it as is and expect that error to bubble up.

2024-01-24 04:17 UTC, seth127 commented
In effect, this means that the current state _actually tweaks non-informative priors too._ **The big question from me: is it ok for us to tweak the non-informative priors the same way that we tweak the initial parameter estimates?**

If so, then we can just document that behavior and move on. 

If that's not ok... then I'm not sure what the next step is. I guess I'd just say "let's cross that bridge when we come to it" (and hope we don't come to it).

@curtisKJ @timwaterhouse could either of you weigh in on my "big question" at the top of this comment?

One final note (in favor of leaving as is): anecdotally, in most cases I've seen, the non-informative priors use `FIX`. In that case, they wouldn't be tweaked anyway. I'm not sure if that's "standard practice" or not, but I thought it was worth noting.

2024-01-24 14:11 UTC, kyleam commented
Thanks @seth127.  I haven't reviewed this PR or been involved in many of the design discussions, so it's helpful to see you expand on those details.

> @kyleam I think you're saying we should just let this case fall through to [this error](https://github.com/metrumresearchgroup/nmrec/blob/2885bc0/R/set-param.R#L189-L204)

In the linked thread, I had assumed that would trigger, but for the latest comment here I took for granted @barrettk's claim that that doesn't get triggered.  (Thank you both for pointing that out.)

So, in the comment above, I was just casting my vote for documenting that this feature is not meant to be used with uninformative prior names, accepting that it will jitter them if there (i.e. your "document that behavior and move on").

A few more thoughts:

 * IIUC the common workflow here is "inherit_param_estimates then tweak", in which case the first step would flag control stream that are using non-informative names.  So in practice it seems to me that this problem would often be flagged.

 * If bbr wanted to give an error in most cases, could abort if there is a `$PRIOR` record and _not_ any informative record names?  That'd hopefully not have false positives, and I think it might catch most cases, though it would miss some (e.g. [subroutine used instead of prior record](https://github.com/metrumresearchgroup/nmrec/pull/18#issuecomment-1830138632)).

 * Or it's perhaps worth considering reworking things so that jittering is coupled to estimates from a previous model.  You could still use `nmrec::extract_*` to get information to intersect, but the core init values could come from a previous model, and you could reliably error on a shape mismatch.  However, I guess that's probably being avoided in anticipation for cases where "tweak estimates" might be used to blow out a series of models for assessing sensitivity of the results to the initial values, in which case requiring a finished model as the starting point would be a bit odd (but maybe not too bad in practice). 

 * It's perhaps worth emphasizing in the docs that these are tools meant to help modelers modify the control stream, but they should review the result very carefully, as if they were writing the model by hand or reviewing changes a person was proposing.  (I haven't taken a look at the documentation that exists, so apologies if this is already there.)

2024-01-24 15:44 UTC, seth127 commented
Thanks @kyleam I appreciate those thoughts. You said

> IIUC the common workflow here is "inherit_param_estimates then tweak", in which case the first step would flag control streams that are using non-informative names. So in practice it seems to me that this problem would often be flagged.

I actually had this same thought this morning. That's reassuring, and I think will likely cover a lot of cases.

To be clear (for anyone else reading this), we're talking about a pattern like this, which several people have mentioned wanting to be able to do:

```r
mod2 <- mod1 %>%
    copy_model_from() %>%
    inherit_param_estimates() %>%
    tweak_initial_estimates()
```

In that case, if `mod1` was using non-informative priors, the [error I mentioned above](https://github.com/metrumresearchgroup/bbr/pull/635#issuecomment-1907345973) would be triggered by the `inherit_param_estimates()` call, before we even get to the `tweak_initial_estimates()` function that we're discussing here.

----

We're going to discuss with a few scientific folks offline. Unless they object, I'm leaning towards this

> documenting that this feature is not meant to be used with uninformative prior names, accepting that it will jitter them if there

2024-01-25 21:19 UTC, seth127 commented
I had said

> We're going to discuss with a few scientific folks offline. Unless they object, I'm leaning towards 
>  > documenting that this feature is not meant to be used with uninformative prior names, accepting that it will jitter them if there

Unfortunately, @timwaterhouse and @curtisKJ do object. Essentially, they said we definitely don't want to tweak the priors. Two things we're going to look into:

1. Look at the NONMEM docs to verify whether you _need to_ specify `FIX` for a parameter record to function as non-informative prior. If the answer is "yes", then this solves our problem, because we don't tweak those values anyway.
2. Look into ways that we can reliably tell whether a given parameter record is an real parameter or a non-informative prior. Basically, restart [this discussion](https://github.com/metrumresearchgroup/nmrec/pull/18#issuecomment-1830138632) about whether the `$PRIOR` block is sufficient and, if not, what else we would need to check.

@barrettk I believe you're taking this ^ on, right?

2024-01-25 21:42 UTC, kyleam commented
> Unfortunately, @timwaterhouse and @curtisKJ do object. Essentially, they said we definitely don't want to tweak the priors. 

The proposal isn't that any wants to tweak them.  It's just accepting that the caller can violated the documented use in a way that leads to them being tweaked.  Was the conclusion "we're going to insist that the outcome is severe enough that we really want to prevent that mistake"?

> Two things we're going to look into:

Perhaps it's worth considering rethinking the design to always use an executed model as the starting point (my "reworking things so that jittering is coupled to estimates from a previous model" bullet point above).  That'd give you a reliable answer to what the shape should be.

2024-01-25 22:14 UTC, kyleam commented
Just a few comments, in case it's helpful...

> Look at the NONMEM docs to verify whether you _need to_ specify `FIX` for a parameter record to function as non-informative prior. If the answer is "yes", then this solves our problem, because we don't tweak those values anyway.

At least based on the nwpri docs, it looks like that could be the case.  I see a lot of "values on these records must be fixed", but perhaps a closer look would show cases where that's not said or perhaps there are other more relevant docs.

> [...] about whether the `$PRIOR` block is sufficient

My conclusion that the prior block isn't sufficient is based on the nwpri docs saying "a $PRIOR record may be used instead of a user-written PRIOR subroutine, in which case the input arguments listed above may be specified as options of $PRIOR".

2024-01-26 14:50 UTC, barrettk commented
In response to @seth127's comment:
>Look at the NONMEM docs to verify whether you need to specify FIX for a parameter record to function as non-informative prior. If the answer is "yes", then this solves our problem, because we don't tweak those values anyway.

Seth and I talked offline about this. It is still something worth looking into, but we decided it isnt really a complete solution, as we want to be able to identify prior records in order to remove them from `initial_estimates()` output. This may not be totally feasible, but the motivation for this is strong, and it was determined that we should see what can be done here.

In response to @kyleam's comments:
> The proposal isn't that anyone wants to tweak them. It's just accepting that the caller can violate the documented use in a way that leads to them being tweaked. Was the conclusion "we're going to insist that the outcome is severe enough that we really want to prevent that mistake"?

The conclusion is that we needed to _guarantee priors wouldnt be altered_, even using the old method. It's apparently a large deal so we need some method of _determining if priors are being used_ at the minimum. Identifying the specific records that are priors is ideal, but we need to at least know if they're being used.

>Perhaps it's worth considering rethinking the design to always use an executed model as the starting point (my "reworking things so that jittering is coupled to estimates from a previous model" bullet point above). That'd give you a reliable answer to what the shape should be.

The jittering feature has to be separate from the `inherit_param_estimates()` function unfortunately, as we want `tweak_initial_estimates()` to be usable on its own. Ideally we dont want to require it to be a previously run model. There have been discussions on creating a wrapper around `tweak_initial_estimates()` to quickly create a bunch of new models with different initial estimates. 
 - These reasons dont technically prohibit what you're suggesting though. I think that is worth considering if we get stuck, though I think there is a strong preference not to require a previously run model. I'd like to hear @seth127's opinion on it, but I know we want to look into how feasible parsing the various ways of specifying priors would be. @curtisKJ suggested there was one really old method that few people were even aware of, but that one or two methods cover the vast majority of cases (one being the `$PRIOR` block, need to look more into the other). I think if we could look for the presence of those two blocks, and make as many inferences as we can (with good documentation on its limitations/warnings), that would be the most preferable option by far.

2024-01-26 14:59 UTC, kyleam commented
> I think if we could look for the presence of those two blocks, and make as many inferences as we can (with good documentation on its limitations/warnings), that would be the most preferable option by far.

It seems to me that that line of thinking is in direct contradiction to claiming you must "guarantee priors wouldnt be altered".

> The jittering feature has to be separate from the `inherit_param_estimates()` function unfortunately, as we want `tweak_initial_estimates()` to be usable on its own

I understand that (I think, at least).  My suggestion is that you reconsider that design decision due to the desire to reliably know if there is a shape mismatch due to prior use.  If we decide not to go that direction, that's of course fine, but here it feels like you're just dismissing the suggestion by reasserting what's already a given.

2024-01-30 15:27 UTC, seth127 commented
# Proposed path forward on priors

I talked with @barrettk for bit yesterday and I have a proposed path forward that I'd love some feedback on:

* We are pretty confident from the NONMEM docs that **non-informative priors must be fixed.** This is great news because **it means that our function would [_not_ tweak them](https://github.com/metrumresearchgroup/bbr/blob/c616be44cc5a868fd59302dffc6370db23599bdc/R/tweak-initial-estimates.R#L75-L77)**, regardless of whether it "knows" they are priors and not regular parameters. (@barrettk can maybe find more, but one example is in the `nwpri.utl` page in NM75 manual, which says "these records must be fixed" in three different places.)
* Given this ^, I have less concern about _not_ being able know which are non-informative priors, because our primary constraint was that we didn't want to tweak them erroneously. Now we know that we won't.
* I propose that we have a fairly simple heuristic (details below) to check if we _think_ they are using non-informative priors, and then give a warning that these are not supported (notably, `initial_estimates()` will return them as if they're regular parameters) and suggest they switch to informative priors.
* Then we move on with the tweak because, as noted above, we won't actually tweak the priors (because they'll be fixed).

Thoughts on that? Anything that I'm missing?

## Details

Here is some pseudo-code I threw together with the heuristic I have in mind:

<details><summary>bbr:::using_old_priors</summary>

```r
#' This function uses a simple heuristic to decide
#' whether the control stream appears to be using the old
#' "non-informative" method of specifying priors
bbr:::using_old_priors(.ctl) {
  # check if PRIORS are being used
  prior_recs <- nmrec::select_records(.ctl, "prior")
  prior_subs <- nmrec::select_records(.ctl, "sub")
  prior_subs <- any(stringr::str_detect(prior_subs, "PRIOR")) # probably want nmrec to parse to see if PRIOR shows up in here...

  # check if INFORMATIVE style is present
  informative_priors <- purrr::walk(
    c("thetap", "thetapv", "omegap", "omegapd", "sigmap", "sigmapd"), # ARE THERE OTHERS???
    ~ {nmrec::select_records(.ctl, .x)}
  )    
  
  # if priors are specified AND _not_ using informative style, then assume using old style
  if (
      ((length(prior_recs) || length(prior_subs)) > 0) && 
      length(informative_priors) == 0   
    ) {
    return(TRUE)
  }
  return(FALSE)
}
```
</details>

Then we call that in `initial_estimates()` (maybe [here](https://github.com/metrumresearchgroup/bbr/blob/c616be44cc5a868fd59302dffc6370db23599bdc/R/initial-estimates.R#L86)) with a message something like this:

```r
if (isTRUE(using_old_priors(ctl))) {
  rlang::warn(paste(
    "This model appears to be using the old 'non-informative' method of specifying priors.",
    "That will cause this function to extract and display priors as if they are initial parameter estimates.",
    "Consider changing the model to use informative prior record names (such as THETAP and THETAPV)."
  ))
}
```

and then we go on with our day...

2024-01-30 17:38 UTC, barrettk commented
Still working on some matrix stuff before I commit the latest changes, but here are some examples of getting the initial estimates, based on some of the above discussion (including @seth127's most recent comment):


<details closed>
<summary>Example with no priors (`MOD1`)</summary>

```r
> initial_estimates(.mod)
# A tibble: 8 × 6
  parameter_names record_type  init lower_bound upper_bound record_number
  <chr>           <chr>       <dbl>       <dbl>       <dbl>         <int>
1 THETA(1)        theta        2              0          NA             1
2 THETA(2)        theta        3              0          NA             1
3 THETA(3)        theta       10              0          NA             1
4 THETA(4)        theta        0.02          NA          NA             1
5 THETA(5)        theta        1             NA          NA             1
6 OMEGA(1,1)      omega        0.05          NA          NA             1
7 OMEGA(2,2)      omega        0.2           NA          NA             1
8 SIGMA(1,1)      sigma        1             NA          NA             1
```
</details>

<details closed>
<summary>Example when using informative priors</summary>

```r
> initial_estimates(.mod)
# A tibble: 15 × 6
   parameter_names record_type    init lower_bound upper_bound record_number
   <chr>           <chr>         <dbl>       <dbl>       <dbl>         <int>
 1 THETA(1)        theta        -0.574          NA          NA             1
 2 THETA(2)        theta         5.67           NA          NA             1
 3 THETA(3)        theta         1.04           NA          NA             1
 4 THETA(4)        theta         0.242          NA          NA             1
 5 THETA(5)        theta       -11.4            NA          NA             1
 6 THETA(6)        theta         5.11           NA          NA             1
 7 OMEGA(1,1)      omega         0.09           NA          NA             1
 8 OMEGA(2,2)      omega         0.09           NA          NA             2
 9 OMEGA(3,2)      omega         0.01           NA          NA             2
10 OMEGA(4,2)      omega         0.01           NA          NA             2
11 OMEGA(3,3)      omega         0.09           NA          NA             2
12 OMEGA(4,3)      omega         0.01           NA          NA             2
13 OMEGA(4,4)      omega         0.09           NA          NA             2
14 SIGMA(1,1)      sigma         0.04           NA          NA             1
15 SIGMA(2,2)      sigma         0.04           NA          NA             1
```
</details>

<details closed>
<summary>Example when ***not*** using informative priors</summary>

```r
> initial_estimates(.mod)
# A tibble: 33 × 6
   parameter_names record_type  init lower_bound upper_bound record_number
   <chr>           <chr>       <dbl>       <dbl>       <dbl>         <int>
 1 THETA(1)        theta         0.7          NA          NA             1
 2 THETA(2)        theta         0.7          NA          NA             1
 3 THETA(3)        theta         2            NA          NA             1
 4 THETA(4)        theta         2            NA          NA             1
 5 THETA(5)        theta         0.7          NA          NA             1
 6 THETA(6)        theta         0.7          NA          NA             1
 7 THETA(7)        theta         2            NA          NA             1
 8 THETA(8)        theta         2            NA          NA             1
 9 THETA(9)        theta         0.7          NA          NA             1
10 THETA(10)       theta         0.7          NA          NA             1
# ℹ 23 more rows
# ℹ Use `print(n = ...)` to see more rows
Warning message:
! This model appears to be using the old 'non-informative' method of specifying priors.
ℹ  - That will cause this function to extract and display priors *as if* they are initial parameter estimates.
ℹ  - Consider changing the model to use informative prior record names (such as THETAP and THETAPV). 
```
</details>

2024-01-30 21:19 UTC, timwaterhouse commented
@seth127 Your proposal looks reasonable to me as well. My only suggestion would be to change the language for "informative" and "non-informative" record names, since that has specific meaning for Bayesian priors. I know the NONMEM documentation calls them that, but I think something like this might be more clear:

```r
if (isTRUE(using_old_priors(ctl))) {
  rlang::warn(paste(
    "This model appears to be using $THETA, $OMEGA, and/or $SIGMA to specify priors.",
    "That will cause this function to extract and display priors as if they are initial parameter estimates.",
    "Consider changing the model to use the more specific prior record names (such as $THETAP and $THETAPV)."
  ))
}
```

2024-01-30 21:22 UTC, barrettk commented
@timwaterhouse The only issue with changing the naming convention, is that `nmrec` also uses those names. I think we'd want those to be consistent, so if this is important, I think we'd want to make the change in both places.

2024-01-31 20:56 UTC, closed without merging